version: '3.8'

services:
  app:
    build:
      context: ./back
      dockerfile: ../Dockerfile
    image: ox_test_app
    container_name: ox_test_app
    restart: unless-stopped
    volumes:
      - ./back:/var/www
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
    networks:
      - ox_test

  react-app:
    build:
      context: ./front
    image: react_app
    container_name: react_app
    restart: unless-stopped
    volumes:
      - ./front:/usr/src/app
    ports:
      - "3000:3000"  # React default port
    command: ["npm", "start"]
    networks:
      - ox_test

  db:
    image: mysql:8.0
    container_name: ox_test_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - ox_test

  nginx:
    image: nginx:latest
    container_name: ox_test_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./back:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - ox_test

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ox_test_phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"  # Access phpMyAdmin at http://localhost:8081
    environment:
      PMA_HOST: db
      PMA_USER: laravel
      PMA_PASSWORD: secret
    networks:
      - ox_test
volumes:
  dbdata:

networks:
  ox_test:
    driver: bridge
